# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MediaStats-iOS-ObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MediaStats-iOS-Objc
  pod 'NERtcSDK', '4.3.8'

end
