# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoStream-iOS-ObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NERtcSDK', '~> 3.6.0'
 
  pod 'Toast'


  target 'VideoStream-iOS-ObjCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
