# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AudioStream-iOS-ObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NERtcSDK', '~> 4.3.8'

  # Pods for AudioStream-iOS-ObjC

  target 'AudioStream-iOS-ObjCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
