# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Beauty-iOS-ObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NERtcSDK', '4.6.53'
  pod 'SSZipArchive', '2.4.3'
  pod 'Masonry', '1.1.0'

end
