# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NERtcSample-ScreenShare-iOS-Objective-C' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NERtcSample-ScreenShare-iOS-Objective-C
  pod 'NERtcSDK', '4.3.0'


end

target 'NERtcSample-ScreenShare-iOS-Objective-C-Broadcast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NERtcSample-ScreenShare-iOS-Objective-C-Broadcast

end
