# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Beauty-iOS-ObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NERtcSDK', '4.3.8'
  pod 'Nama-lite', '7.1.2'

end
