#############################################################################
# Makefile for building: bin/1v1_beauty.app/Contents/MacOS/1v1_beauty
# Generated by qmake (3.1) (Qt 6.2.0)
# Project:  beauty_prj.pro
# Template: app
# Command: /Users/robin/Qt/6.2.0/macos/bin/qmake -o 1v1_beauty.xcodeproj/project.pbxproj beauty_prj.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/robin/Qt/6.2.0/macos/bin/qmake
1v1_beauty.xcodeproj/project.pbxproj: beauty_prj.pro /Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang/qmake.conf /Users/robin/Qt/6.2.0/macos/mkspecs/features/spec_pre.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/device_config.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/common/unix.conf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/common/mac.conf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/common/macx.conf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/common/sanitize.conf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/common/gcc-base.conf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/common/clang.conf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/common/clang-mac.conf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/qconfig.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/qt_functions.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/qt_config.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang/qmake.conf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/macx-xcode/qmake.conf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/exclusive_builds.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/sdk.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/toolchain.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/toolchain.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/default_pre.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/default_pre.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/resolve_config.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/default_post.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/default_post.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/objective_c.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/mac.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/warn_on.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/qt.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/resources_functions.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/resources.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/moc.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/unix/opengl.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/uic.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/unix/thread.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/qmake_use.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/file_copies.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/rez.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/testcase_targets.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/exceptions.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/yacc.prf \
		/Users/robin/Qt/6.2.0/macos/mkspecs/features/lex.prf \
		beauty_prj.pro \
		source/resource/image.qrc \
		qmake_qmake_immediate.qrc \
		/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Resources/QtGui.prl \
		/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o 1v1_beauty.xcodeproj/project.pbxproj beauty_prj.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
/Users/robin/Qt/6.2.0/macos/mkspecs/features/spec_pre.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/device_config.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/common/unix.conf:
/Users/robin/Qt/6.2.0/macos/mkspecs/common/mac.conf:
/Users/robin/Qt/6.2.0/macos/mkspecs/common/macx.conf:
/Users/robin/Qt/6.2.0/macos/mkspecs/common/sanitize.conf:
/Users/robin/Qt/6.2.0/macos/mkspecs/common/gcc-base.conf:
/Users/robin/Qt/6.2.0/macos/mkspecs/common/gcc-base-mac.conf:
/Users/robin/Qt/6.2.0/macos/mkspecs/common/clang.conf:
/Users/robin/Qt/6.2.0/macos/mkspecs/common/clang-mac.conf:
/Users/robin/Qt/6.2.0/macos/mkspecs/qconfig.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_ext_freetype.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_ext_libpng.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_concurrent.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_core.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_core_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_dbus.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_designer.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_designer_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_gui.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_gui_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_help.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_help_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsanimation.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssettings.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_linguist.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_linguist_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_network.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_network_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_opengl.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_printsupport.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qml.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qml_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlcore.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmltest.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quick_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sql.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_sql_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svg.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svg_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_testlib.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_tools_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_uitools.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_widgets.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_xml.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/modules/qt_lib_xml_private.pri:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/qt_functions.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/qt_config.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang/qmake.conf:
/Users/robin/Qt/6.2.0/macos/mkspecs/macx-xcode/qmake.conf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/exclusive_builds.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/sdk.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/toolchain.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/toolchain.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/default_pre.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/default_pre.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/resolve_config.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/default_post.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/default_post.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/objective_c.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/mac.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/warn_on.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/qt.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/resources_functions.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/resources.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/moc.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/unix/opengl.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/uic.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/unix/thread.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/qmake_use.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/file_copies.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/rez.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/mac/asset_catalogs.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/testcase_targets.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/exceptions.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/yacc.prf:
/Users/robin/Qt/6.2.0/macos/mkspecs/features/lex.prf:
beauty_prj.pro:
source/resource/image.qrc:
qmake_qmake_immediate.qrc:
/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Resources/QtGui.prl:
/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o 1v1_beauty.xcodeproj/project.pbxproj beauty_prj.pro -spec macx-xcode

qmake_all: FORCE

