#############################################################################
# Makefile for building: bin/1v1_beauty.app/Contents/MacOS/1v1_beauty
# Generated by qmake (3.1) (Qt 6.2.0)
# Project:  beauty_prj.pro
# Template: app
# Command: /Users/robin/Qt/6.2.0/macos/bin/qmake -o 1v1_beauty.xcodeproj/project.pbxproj beauty_prj.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

MOC       = /Users/robin/Qt/6.2.0/macos/libexec/moc
UIC       = /Users/robin/Qt/6.2.0/macos/libexec/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH       = -I. -I. -I3rdparty/nertc/mac/NEFundation_Mac.framework/Headers -I3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers -I3rdparty/jsoncpp/include/mac -Isource/include -I/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang -F/Users/robin/Qt/6.2.0/macos/lib
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: qrc_image.cpp qrc_qmake_qmake_immediate.cpp moc_beauty_item_widget.cpp moc_beauty_tabwidget.cpp moc_call_widget.cpp\
	 moc_engine.cpp moc_face_beauty_widget.cpp moc_filter_beauty_widget.cpp\
	 moc_item_sticker_widget.cpp moc_join_widget.cpp moc_other_beauty_widget.cpp\
	 moc_room_button.cpp moc_skin_beauty_widget.cpp
compiler_rcc_make_all: qrc_image.cpp qrc_qmake_qmake_immediate.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_image.cpp qrc_qmake_qmake_immediate.cpp
qrc_image.cpp: source/resource/image.qrc \
		/Users/robin/Qt/6.2.0/macos/libexec/rcc \
		source/resource/image/setting.png \
		source/resource/image/cancel_call.png \
		source/resource/image/networkquality_general.svg \
		source/resource/image/radio-check.png \
		source/resource/image/triangle-down.png \
		source/resource/image/right_white.svg \
		source/resource/image/networkquality_bad.svg \
		source/resource/image/smlie-active.svg \
		source/resource/image/networkquality_good.svg \
		source/resource/image/radio-uncheck.png \
		source/resource/image/voice-on.png \
		source/resource/image/triangle-combox.png \
		source/resource/image/device_selector_normal.png \
		source/resource/image/thumb-up-active.svg \
		source/resource/image/video-on.png \
		source/resource/image/check.png \
		source/resource/image/background.png \
		source/resource/image/device_selector_pushed.png \
		source/resource/image/beauty-off.png \
		source/resource/image/thumbs-down-active.svg \
		source/resource/image/thumb-up.svg \
		source/resource/image/clear.png \
		source/resource/image/video-off.png \
		source/resource/image/beaut-on.png \
		source/resource/image/zoomIn.png \
		source/resource/image/data.png \
		source/resource/image/thumbs-down.svg \
		source/resource/image/btn_show_device_normal.png \
		source/resource/image/networkquality_unknown.svg \
		source/resource/image/voice-off.png \
		source/resource/image/zoomOut.png \
		source/resource/image/normal.png
	/Users/robin/Qt/6.2.0/macos/libexec/rcc -name image source/resource/image.qrc -o qrc_image.cpp

qrc_qmake_qmake_immediate.cpp: qmake_qmake_immediate.qrc \
		/Users/robin/Qt/6.2.0/macos/libexec/rcc \
		source/resource/image/cancel_call.png \
		source/resource/image/networkquality_bad.svg \
		source/resource/image/triangle-combox.png \
		source/resource/image/check.png \
		source/resource/image/background.png \
		source/resource/image/device_selector_pushed.png \
		source/resource/image/beauty-off.png \
		source/resource/image/thumbs-down-active.svg \
		source/resource/image/clear.png \
		source/resource/image/btn_show_device_normal.png \
		source/resource/image/networkquality_unknown.svg \
		source/resource/image/voice-off.png \
		source/resource/image/networkquality_general.svg \
		source/resource/image/radio-check.png \
		source/resource/image/triangle-down.png \
		source/resource/image/right_white.svg \
		source/resource/image/networkquality_good.svg \
		source/resource/image/radio-uncheck.png \
		source/resource/image/smlie-active.svg \
		source/resource/image/voice-on.png \
		source/resource/image/device_selector_normal.png \
		source/resource/image/thumb-up-active.svg \
		source/resource/image/btn_show_device_down_normal.png \
		source/resource/image/video-on.png \
		source/resource/image/thumb-up.svg \
		source/resource/image/video-off.png \
		source/resource/image/beaut-on.png \
		source/resource/image/zoomIn.png \
		source/resource/image/data.png \
		source/resource/image/setting.png \
		source/resource/image/thumbs-down.svg \
		source/resource/image/zoomOut.png \
		source/resource/image/normal.png
	/Users/robin/Qt/6.2.0/macos/libexec/rcc -name qmake_qmake_immediate qmake_qmake_immediate.qrc -o qrc_qmake_qmake_immediate.cpp

compiler_moc_header_make_all: moc_beauty_item_widget.cpp moc_beauty_tabwidget.cpp moc_call_widget.cpp moc_engine.cpp moc_face_beauty_widget.cpp moc_filter_beauty_widget.cpp moc_item_sticker_widget.cpp moc_join_widget.cpp moc_other_beauty_widget.cpp moc_room_button.cpp moc_skin_beauty_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_beauty_item_widget.cpp moc_beauty_tabwidget.cpp moc_call_widget.cpp moc_engine.cpp moc_face_beauty_widget.cpp moc_filter_beauty_widget.cpp moc_item_sticker_widget.cpp moc_join_widget.cpp moc_other_beauty_widget.cpp moc_room_button.cpp moc_skin_beauty_widget.cpp
moc_beauty_item_widget.cpp: source/include/beauty_item_widget.h \
		/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/robin/Qt/6.2.0/macos/libexec/moc
	/Users/robin/Qt/6.2.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/NEFundation_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/jsoncpp/include/mac -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/source/include -I/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/robin/Qt/6.2.0/macos/lib source/include/beauty_item_widget.h -o moc_beauty_item_widget.cpp

moc_beauty_tabwidget.cpp: source/include/beauty_tabwidget.h \
		/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers/QDialog \
		/Users/robin/Qt/6.2.0/macos/libexec/moc
	/Users/robin/Qt/6.2.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/NEFundation_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/jsoncpp/include/mac -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/source/include -I/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/robin/Qt/6.2.0/macos/lib source/include/beauty_tabwidget.h -o moc_beauty_tabwidget.cpp

moc_call_widget.cpp: source/include/call_widget.h \
		/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/robin/Qt/6.2.0/macos/libexec/moc
	/Users/robin/Qt/6.2.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/NEFundation_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/jsoncpp/include/mac -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/source/include -I/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/robin/Qt/6.2.0/macos/lib source/include/call_widget.h -o moc_call_widget.cpp

moc_engine.cpp: source/include/engine.h \
		/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers/QObject \
		3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers/nertc_engine_ex.h \
		/Users/robin/Qt/6.2.0/macos/libexec/moc
	/Users/robin/Qt/6.2.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/NEFundation_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/jsoncpp/include/mac -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/source/include -I/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/robin/Qt/6.2.0/macos/lib source/include/engine.h -o moc_engine.cpp

moc_face_beauty_widget.cpp: source/include/face_beauty_widget.h \
		/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers/QVector \
		3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers/nertc_engine_defines.h \
		/Users/robin/Qt/6.2.0/macos/libexec/moc
	/Users/robin/Qt/6.2.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/NEFundation_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/jsoncpp/include/mac -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/source/include -I/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/robin/Qt/6.2.0/macos/lib source/include/face_beauty_widget.h -o moc_face_beauty_widget.cpp

moc_filter_beauty_widget.cpp: source/include/filter_beauty_widget.h \
		/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers/QVector \
		/Users/robin/Qt/6.2.0/macos/libexec/moc
	/Users/robin/Qt/6.2.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/NEFundation_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/jsoncpp/include/mac -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/source/include -I/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/robin/Qt/6.2.0/macos/lib source/include/filter_beauty_widget.h -o moc_filter_beauty_widget.cpp

moc_item_sticker_widget.cpp: source/include/item_sticker_widget.h \
		/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers/QVector \
		/Users/robin/Qt/6.2.0/macos/libexec/moc
	/Users/robin/Qt/6.2.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/NEFundation_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/jsoncpp/include/mac -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/source/include -I/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/robin/Qt/6.2.0/macos/lib source/include/item_sticker_widget.h -o moc_item_sticker_widget.cpp

moc_join_widget.cpp: source/include/join_widget.h \
		/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		source/include/call_widget.h \
		/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/robin/Qt/6.2.0/macos/libexec/moc
	/Users/robin/Qt/6.2.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/NEFundation_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/jsoncpp/include/mac -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/source/include -I/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/robin/Qt/6.2.0/macos/lib source/include/join_widget.h -o moc_join_widget.cpp

moc_other_beauty_widget.cpp: source/include/other_beauty_widget.h \
		/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/robin/Qt/6.2.0/macos/libexec/moc
	/Users/robin/Qt/6.2.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/NEFundation_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/jsoncpp/include/mac -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/source/include -I/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/robin/Qt/6.2.0/macos/lib source/include/other_beauty_widget.h -o moc_other_beauty_widget.cpp

moc_room_button.cpp: source/include/room_button.h \
		/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/robin/Qt/6.2.0/macos/libexec/moc
	/Users/robin/Qt/6.2.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/NEFundation_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/jsoncpp/include/mac -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/source/include -I/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/robin/Qt/6.2.0/macos/lib source/include/room_button.h -o moc_room_button.cpp

moc_skin_beauty_widget.cpp: source/include/skin_beauty_widget.h \
		/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers/QVector \
		3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers/nertc_engine_defines.h \
		/Users/robin/Qt/6.2.0/macos/libexec/moc
	/Users/robin/Qt/6.2.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/robin/Qt/6.2.0/macos/mkspecs/macx-clang -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/NEFundation_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/nertc/mac/nertc_sdk_Mac.framework/Headers -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/3rdparty/jsoncpp/include/mac -I/Users/robin/01-workspace/netease/SampleCode/nebeauty/nebeauty-sample/Mac/beauty_prj/source/include -I/Users/robin/Qt/6.2.0/macos/lib/QtWidgets.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtGui.framework/Headers -I/Users/robin/Qt/6.2.0/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/robin/Qt/6.2.0/macos/lib source/include/skin_beauty_widget.h -o moc_skin_beauty_widget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

